/*
 * Project Euler
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
#include <stdio.h>
#include <stdint.h>

int main( int argc, char *argv[] )
{
	uint32_t sum = 0 ;
	uint32_t prev_fib = 1 ;
	uint32_t current_fib = 2 ;
	uint32_t temp = 0 ;
	static const uint32_t MAX = 4000000 ;

	do {
		// calculate if even and if so add to sum
		if ( (current_fib % 2) == 0 )
			sum += current_fib ;

		// get next fib number
		temp = prev_fib + current_fib ;
		prev_fib = current_fib ;
		current_fib = temp ;

	} while ( current_fib < MAX ) ;

	printf( "The sum is %d\n", sum ) ;
	
	return 0 ;
}
